defaults:
  slim:
    debug: false

  activerecord:
    host: "localhost"
    user:
    pass:
    name:

  elasticsearch:
    client:
      servers:
        - host: "localhost"
          port: 9200
    indexes:
      example:
        number_of_shards: 5
        number_of_replicas: 1
        analysis:
          analyzer:
            indexAnalyzer:
              type: "standard"
              tokenizer: "standard"
            searchAnalyzer:
              type: "standard"
              tokenizer: "standard"


development:
  slim:
    debug: true
  activerecord:
    user: "root"
    pass:
    name:

